services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: shoes_shop
    networks:
      springboot-mysql-net:
    volumes:
      - my-data-volume:/var/lib/mysql/
#    restart: on-failure

  back-end:
    container_name: shoes-shop-backend
    image: duybroooo/shoes-shop-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
#    restart: on-failure

networks:
  springboot-mysql-net:
volumes:
  my-data-volume: